language: python
cache: pip
matrix:
  fast_finish: true
  include:
  - env: TOXENV=black
  - env: TOXENV=flake8
  - env: TOXENV=isort
  - env: TOXENV=docs
  - python: 3.5
    env: TOXENV=py35-django111
  - python: 3.6
    env: TOXENV=py36-django111
  - python: 3.7
    env: TOXENV=py37-django111
  - python: 3.5
    env: TOXENV=py35-django22
  - python: 3.6
    env: TOXENV=py36-django22
  - python: 3.7
    env: TOXENV=py37-django22
  - python: 3.8
    env: TOXENV=py38-django22
  - python: 3.6
    env: TOXENV=py36-django30
  - python: 3.7
    env: TOXENV=py37-django30
  - python: 3.8
    env: TOXENV=py38-django30
  - python: 3.6
    env: TOXENV=py36-djangomaster
  - python: 3.7
    env: TOXENV=py37-djangomaster
  - python: 3.8
    env: TOXENV=py38-djangomaster
  allow_failures:
  - env: TOXENV=py36-djangomaster
  - env: TOXENV=py37-djangomaster
  - env: TOXENV=py38-djangomaster
install:
- pip install tox
script:
- tox
after_success:
- pip install codecov
- codecov -e TOXENV CI TRAVIS_BUILD_ID TRAVIS TRAVIS_BRANCH TRAVIS_JOB_NUMBER TRAVIS_PULL_REQUEST
  TRAVIS_JOB_ID TRAVIS_REPO_SLUG TRAVIS_COMMIT
deploy:
  provider: pypi
  user: jazzband
  distribution: sdist bdist_wheel
  server: https://jazzband.co/projects/django-taggit/upload
  password:
    secure: ky+UZnCbKb213Ohqnv2uEfef3vXv1JoAaG5vCjR6Xspf+Ahz4F/4oKe5Noo/xxnRs1x8bjDfYFIbQVQYKyM95dJ7VVQWtrwjId+NMCE9K36l1qC199eCUxkYd/jPg6iM8no4gXa3AOyam+j2yMhAgqfM1YKMNFW7j1kR+T7cz4A=
  on:
    tags: true
    repo: jazzband/django-taggit
    condition: "$TOXENV=py38-django30"
notifications:
  email: false
