language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=https://github.com/django/django/archive/master.tar.gz
  - DJANGO=django==1.6
  - DJANGO=django==1.5.5
  - DJANGO=django==1.4.10

install:
  - pip install $DJANGO
  - pip install -r requirements/travis-ci.txt --use-mirrors

script:
  - coverage run --source django_taggit runtests.py
  - coverage report

notifications:
  email: false

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=django==1.4.10
    - python: "3.3"
      env: DJANGO=django==1.4.10
    - python: "2.6"
      env: DJANGO=https://github.com/django/django/archive/master.tar.gz

